/*
 * This file is generated by jOOQ.
 */
package de.maaanu.jooq.public_.tables.daos;


import de.maaanu.PrivilegeType;
import de.maaanu.jooq.public_.tables.Privilege;
import de.maaanu.jooq.public_.tables.records.PrivilegeRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PrivilegeDao extends DAOImpl<PrivilegeRecord, de.maaanu.jooq.public_.tables.pojos.Privilege, Integer> {

    /**
     * Create a new PrivilegeDao without any configuration
     */
    public PrivilegeDao() {
        super(Privilege.PRIVILEGE, de.maaanu.jooq.public_.tables.pojos.Privilege.class);
    }

    /**
     * Create a new PrivilegeDao with an attached configuration
     */
    public PrivilegeDao(Configuration configuration) {
        super(Privilege.PRIVILEGE, de.maaanu.jooq.public_.tables.pojos.Privilege.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(de.maaanu.jooq.public_.tables.pojos.Privilege object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>ID IN (values)</code>
     */
    public List<de.maaanu.jooq.public_.tables.pojos.Privilege> fetchById(Integer... values) {
        return fetch(Privilege.PRIVILEGE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>ID = value</code>
     */
    public de.maaanu.jooq.public_.tables.pojos.Privilege fetchOneById(Integer value) {
        return fetchOne(Privilege.PRIVILEGE.ID, value);
    }

    /**
     * Fetch records that have <code>PRIVILEGE_TYPE IN (values)</code>
     */
    public List<de.maaanu.jooq.public_.tables.pojos.Privilege> fetchByPrivilegeType(PrivilegeType... values) {
        return fetch(Privilege.PRIVILEGE.PRIVILEGE_TYPE, values);
    }

    /**
     * Fetch a unique record that has <code>PRIVILEGE_TYPE = value</code>
     */
    public de.maaanu.jooq.public_.tables.pojos.Privilege fetchOneByPrivilegeType(PrivilegeType value) {
        return fetchOne(Privilege.PRIVILEGE.PRIVILEGE_TYPE, value);
    }
}
