/*
 * This file is generated by jOOQ.
 */
package de.maaanu.jooq.public_.tables.daos;


import de.maaanu.jooq.public_.tables.Role;
import de.maaanu.jooq.public_.tables.records.RoleRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * A table to contain all roles
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RoleDao extends DAOImpl<RoleRecord, de.maaanu.jooq.public_.tables.pojos.Role, Integer> {

    /**
     * Create a new RoleDao without any configuration
     */
    public RoleDao() {
        super(Role.ROLE, de.maaanu.jooq.public_.tables.pojos.Role.class);
    }

    /**
     * Create a new RoleDao with an attached configuration
     */
    public RoleDao(Configuration configuration) {
        super(Role.ROLE, de.maaanu.jooq.public_.tables.pojos.Role.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(de.maaanu.jooq.public_.tables.pojos.Role object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>ID IN (values)</code>
     */
    public List<de.maaanu.jooq.public_.tables.pojos.Role> fetchById(Integer... values) {
        return fetch(Role.ROLE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>ID = value</code>
     */
    public de.maaanu.jooq.public_.tables.pojos.Role fetchOneById(Integer value) {
        return fetchOne(Role.ROLE.ID, value);
    }

    /**
     * Fetch records that have <code>DESCRIPTION IN (values)</code>
     */
    public List<de.maaanu.jooq.public_.tables.pojos.Role> fetchByDescription(String... values) {
        return fetch(Role.ROLE.DESCRIPTION, values);
    }

    /**
     * Fetch a unique record that has <code>DESCRIPTION = value</code>
     */
    public de.maaanu.jooq.public_.tables.pojos.Role fetchOneByDescription(String value) {
        return fetchOne(Role.ROLE.DESCRIPTION, value);
    }
}
