/*
 * This file is generated by jOOQ.
 */
package de.maaanu.jooq.public_.tables.records;


import de.maaanu.jooq.public_.tables.RolePrivilege;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RolePrivilegeRecord extends TableRecordImpl<RolePrivilegeRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = -1424207370;

    /**
     * Setter for <code>PUBLIC.ROLE_PRIVILEGE.ROLE_ID</code>.
     */
    public RolePrivilegeRecord setRoleId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.ROLE_PRIVILEGE.ROLE_ID</code>.
     */
    public Integer getRoleId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>PUBLIC.ROLE_PRIVILEGE.PRIVILEGE_ID</code>.
     */
    public RolePrivilegeRecord setPrivilegeId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.ROLE_PRIVILEGE.PRIVILEGE_ID</code>.
     */
    public Integer getPrivilegeId() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return RolePrivilege.ROLE_PRIVILEGE.ROLE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return RolePrivilege.ROLE_PRIVILEGE.PRIVILEGE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getRoleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getPrivilegeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getRoleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getPrivilegeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RolePrivilegeRecord value1(Integer value) {
        setRoleId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RolePrivilegeRecord value2(Integer value) {
        setPrivilegeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RolePrivilegeRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RolePrivilegeRecord
     */
    public RolePrivilegeRecord() {
        super(RolePrivilege.ROLE_PRIVILEGE);
    }

    /**
     * Create a detached, initialised RolePrivilegeRecord
     */
    public RolePrivilegeRecord(Integer roleId, Integer privilegeId) {
        super(RolePrivilege.ROLE_PRIVILEGE);

        set(0, roleId);
        set(1, privilegeId);
    }
}
