/*
 * This file is generated by jOOQ.
 */
package de.maaanu.jooq.public_;


import de.maaanu.jooq.public_.tables.Databasechangeloglock;
import de.maaanu.jooq.public_.tables.Privilege;
import de.maaanu.jooq.public_.tables.Role;
import de.maaanu.jooq.public_.tables.RolePrivilege;
import de.maaanu.jooq.public_.tables.User;
import de.maaanu.jooq.public_.tables.UserRole;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>PUBLIC</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index PRIMARY_KEY_D = Indexes0.PRIMARY_KEY_D;
    public static final Index CONSTRAINT_INDEX_4 = Indexes0.CONSTRAINT_INDEX_4;
    public static final Index PRIMARY_KEY_4 = Indexes0.PRIMARY_KEY_4;
    public static final Index CONSTRAINT_INDEX_26 = Indexes0.CONSTRAINT_INDEX_26;
    public static final Index PRIMARY_KEY_26 = Indexes0.PRIMARY_KEY_26;
    public static final Index FK_PRIVILEGE2ROLE_INDEX_4 = Indexes0.FK_PRIVILEGE2ROLE_INDEX_4;
    public static final Index FK_ROLE2PRIVILEGE_INDEX_4 = Indexes0.FK_ROLE2PRIVILEGE_INDEX_4;
    public static final Index CONSTRAINT_INDEX_2 = Indexes0.CONSTRAINT_INDEX_2;
    public static final Index PRIMARY_KEY_2 = Indexes0.PRIMARY_KEY_2;
    public static final Index FK_ROLE2USER_INDEX_B = Indexes0.FK_ROLE2USER_INDEX_B;
    public static final Index FK_USER2ROLE_INDEX_B = Indexes0.FK_USER2ROLE_INDEX_B;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index PRIMARY_KEY_D = Internal.createIndex("PRIMARY_KEY_D", Databasechangeloglock.DATABASECHANGELOGLOCK, new OrderField[] { Databasechangeloglock.DATABASECHANGELOGLOCK.ID }, true);
        public static Index CONSTRAINT_INDEX_4 = Internal.createIndex("CONSTRAINT_INDEX_4", Privilege.PRIVILEGE, new OrderField[] { Privilege.PRIVILEGE.PRIVILEGE_TYPE }, true);
        public static Index PRIMARY_KEY_4 = Internal.createIndex("PRIMARY_KEY_4", Privilege.PRIVILEGE, new OrderField[] { Privilege.PRIVILEGE.ID }, true);
        public static Index CONSTRAINT_INDEX_26 = Internal.createIndex("CONSTRAINT_INDEX_26", Role.ROLE, new OrderField[] { Role.ROLE.DESCRIPTION }, true);
        public static Index PRIMARY_KEY_26 = Internal.createIndex("PRIMARY_KEY_26", Role.ROLE, new OrderField[] { Role.ROLE.ID }, true);
        public static Index FK_PRIVILEGE2ROLE_INDEX_4 = Internal.createIndex("FK_PRIVILEGE2ROLE_INDEX_4", RolePrivilege.ROLE_PRIVILEGE, new OrderField[] { RolePrivilege.ROLE_PRIVILEGE.PRIVILEGE_ID }, false);
        public static Index FK_ROLE2PRIVILEGE_INDEX_4 = Internal.createIndex("FK_ROLE2PRIVILEGE_INDEX_4", RolePrivilege.ROLE_PRIVILEGE, new OrderField[] { RolePrivilege.ROLE_PRIVILEGE.ROLE_ID }, false);
        public static Index CONSTRAINT_INDEX_2 = Internal.createIndex("CONSTRAINT_INDEX_2", User.USER, new OrderField[] { User.USER.USERNAME }, true);
        public static Index PRIMARY_KEY_2 = Internal.createIndex("PRIMARY_KEY_2", User.USER, new OrderField[] { User.USER.ID }, true);
        public static Index FK_ROLE2USER_INDEX_B = Internal.createIndex("FK_ROLE2USER_INDEX_B", UserRole.USER_ROLE, new OrderField[] { UserRole.USER_ROLE.ROLE_ID }, false);
        public static Index FK_USER2ROLE_INDEX_B = Internal.createIndex("FK_USER2ROLE_INDEX_B", UserRole.USER_ROLE, new OrderField[] { UserRole.USER_ROLE.USER_ID }, false);
    }
}
