/*
 * This file is generated by jOOQ.
 */
package de.maaanu.jooq.public_;


import de.maaanu.jooq.DefaultCatalog;
import de.maaanu.jooq.public_.tables.Databasechangelog;
import de.maaanu.jooq.public_.tables.Databasechangeloglock;
import de.maaanu.jooq.public_.tables.Privilege;
import de.maaanu.jooq.public_.tables.Role;
import de.maaanu.jooq.public_.tables.RolePrivilege;
import de.maaanu.jooq.public_.tables.User;
import de.maaanu.jooq.public_.tables.UserRole;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -1861682932;

    /**
     * The reference instance of <code>PUBLIC</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>PUBLIC.DATABASECHANGELOG</code>.
     */
    public final Databasechangelog DATABASECHANGELOG = de.maaanu.jooq.public_.tables.Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>PUBLIC.DATABASECHANGELOGLOCK</code>.
     */
    public final Databasechangeloglock DATABASECHANGELOGLOCK = de.maaanu.jooq.public_.tables.Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>PUBLIC.PRIVILEGE</code>.
     */
    public final Privilege PRIVILEGE = de.maaanu.jooq.public_.tables.Privilege.PRIVILEGE;

    /**
     * A table to contain all roles
     */
    public final Role ROLE = de.maaanu.jooq.public_.tables.Role.ROLE;

    /**
     * The table <code>PUBLIC.ROLE_PRIVILEGE</code>.
     */
    public final RolePrivilege ROLE_PRIVILEGE = de.maaanu.jooq.public_.tables.RolePrivilege.ROLE_PRIVILEGE;

    /**
     * A table to contain all users
     */
    public final User USER = de.maaanu.jooq.public_.tables.User.USER;

    /**
     * The table <code>PUBLIC.USER_ROLE</code>.
     */
    public final UserRole USER_ROLE = de.maaanu.jooq.public_.tables.UserRole.USER_ROLE;

    /**
     * No further instances allowed
     */
    private Public() {
        super("PUBLIC", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Databasechangelog.DATABASECHANGELOG,
            Databasechangeloglock.DATABASECHANGELOGLOCK,
            Privilege.PRIVILEGE,
            Role.ROLE,
            RolePrivilege.ROLE_PRIVILEGE,
            User.USER,
            UserRole.USER_ROLE);
    }
}
