/*
 * This file is generated by jOOQ.
 */
package de.maaanu.jooq.public_.tables.pojos;


import de.maaanu.PrivilegeType;

import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Privilege implements Serializable {

    private static final long serialVersionUID = -570717345;

    private Integer       id;
    private PrivilegeType privilegeType;

    public Privilege() {}

    public Privilege(Privilege value) {
        this.id = value.id;
        this.privilegeType = value.privilegeType;
    }

    public Privilege(
        Integer       id,
        PrivilegeType privilegeType
    ) {
        this.id = id;
        this.privilegeType = privilegeType;
    }

    public Integer getId() {
        return this.id;
    }

    public Privilege setId(Integer id) {
        this.id = id;
        return this;
    }

    public PrivilegeType getPrivilegeType() {
        return this.privilegeType;
    }

    public Privilege setPrivilegeType(PrivilegeType privilegeType) {
        this.privilegeType = privilegeType;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Privilege other = (Privilege) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (privilegeType == null) {
            if (other.privilegeType != null)
                return false;
        }
        else if (!privilegeType.equals(other.privilegeType))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.privilegeType == null) ? 0 : this.privilegeType.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Privilege (");

        sb.append(id);
        sb.append(", ").append(privilegeType);

        sb.append(")");
        return sb.toString();
    }
}
